# Site settings
title: "Abrahanfer's blog"
email: abrahanfer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yoopify Stuff
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://abrahanfer.yoopify.com" # the base hostname & protocol for your site
twitter_username: abrahanfer
github_username:  abrahanfer

# Build settings
markdown: kramdown
